import About from "../components/About";
import HomePage from "../components/Home";
import Projects from "../components/Projects";
import Contact from "../components/Contact";
import Skills from "../components/Skills";


export const metadata = {
  title: 'Clodron | Your Web Marketing Agency',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <div>
      <HomePage />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </div>
  );
}